application: zushenyan
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  
- url: /admin
  script: admin.py

- url: /admin/.*
  script: admin.py
  
- url: /.*
  script: request.py

builtins:
- datastore_admin: on
